name: Publish API image
on:
    push:
        branches:
            - main
        paths:
            - api/**

permissions:
    contents: read
    packages: write

jobs:
    push_to_registry:
        runs-on: ubuntu-latest
        name: Build and Push Docker image to Github Packages
        steps:
            - name: Check out repo
              uses: actions/checkout@v3
            - name: Login to GitHub registry
              uses: docker/login-action@v2
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
            - name: Login to ghcr.io
              uses: docker/login-action@v2
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Build and push API
              uses: docker/build-push-action@v4
              with:
                  context: api
                  push: true
                  pull: true
                  tags: |
                        docker.pkg.github.com/code-elevate/engine
                        ghcr.io/code-elevate/engine